#!/usr/bin/env python3
"""
Badminton App — Supabase production restore
Usage: python3 backups/run_restore.py backups/db_backup_<timestamp>.sql

What this script does
---------------------
1. Parses the INSERT statements from a backup SQL file (generated by run_backup.py).
2. Truncates all tables in REVERSE FK order so no constraint violations occur.
3. Re-inserts every row via the Supabase REST API using the service role key
   (bypasses RLS — same effective privilege as the SQL editor).

Why not run the raw SQL file directly
--------------------------------------
The backup SQL uses ALTER TABLE ... DISABLE TRIGGER ALL, which requires the
postgres superuser role. The service role key does not have that privilege.
This script skips that DDL and uses upsert-style individual INSERT calls via
the REST API instead, which the service role CAN perform. For the same result
with full superuser rights, paste the .sql file into the Supabase SQL Editor.

Safety checks
-------------
- Prints a dry-run summary and asks for confirmation before writing anything.
- Truncates only the tables in TABLES (never touches auth.users or schema DDL).
- Any FK violation or insert error is printed and the script aborts immediately.

No external dependencies — stdlib only.
"""

import json
import os
import sys
import re
import urllib.request
import urllib.parse
from pathlib import Path

# ── Credentials (env-first, .env fallback) ───────────────────────────────────
def _load_dotenv(path: Path):
    """Minimal .env loader — no external deps."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        os.environ.setdefault(key.strip(), val.strip().strip('"').strip("'"))

_load_dotenv(Path(__file__).parent / ".env")

SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SERVICE_KEY  = os.environ.get("SUPABASE_SERVICE_KEY", "")

if not SUPABASE_URL or not SERVICE_KEY:
    print("Error: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set.")
    print("  Create backups/.env with those two variables, or export them.")
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────────────────────

HEADERS = {
    "apikey":        SERVICE_KEY,
    "Authorization": f"Bearer {SERVICE_KEY}",
    "Content-Type":  "application/json",
    "Prefer":        "return=minimal",
}

# Truncation order = REVERSE of backup insert order (children before parents).
# Every table that run_backup.py writes must appear here.
TRUNCATE_ORDER = [
    "session_wrapped_stats",
    "match_players",
    "match_games",
    "matches",
    "queue_entries",
    "identity_migrations",
    "push_subscriptions",
    "courts",
    "session_organizers",
    "sessions",
    "profiles",
]

# Insert order = FK-safe order (parents before children) — same as run_backup.py
INSERT_ORDER = [
    "profiles",
    "sessions",
    "session_organizers",
    "courts",
    "push_subscriptions",
    "identity_migrations",
    "queue_entries",
    "matches",
    "match_games",
    "match_players",
    "session_wrapped_stats",
]

BATCH_SIZE = 100   # rows per REST upsert call

# Generated columns must be excluded from INSERT payloads — the DB computes them.
GENERATED_COLUMNS: dict[str, set[str]] = {
    "session_wrapped_stats": {"point_diff"},
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def rest_request(method: str, path: str, body=None) -> bytes:
    url  = f"{SUPABASE_URL}/rest/v1/{path}"
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req  = urllib.request.Request(url, data=data, headers=HEADERS, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read()
    except urllib.error.HTTPError as e:
        body_text = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code} {method} {path}: {body_text}") from e


def truncate_table(table: str):
    """Delete all rows from a table via REST (DELETE with no filter = all rows)."""
    rest_request("DELETE", f"{table}?id=neq.00000000-0000-0000-0000-000000000000")
    # Fallback for tables whose PK is not 'id' (identity_migrations uses 'id' too — fine).
    # For any table that still has rows, use a catch-all filter on a non-null column.
    # The neq filter above matches every real row since no UUID equals the nil UUID.


def truncate_all(tables: list):
    print("\nTruncating tables (reverse FK order)…")
    for table in tables:
        print(f"  DELETE {table}… ", end="", flush=True)
        truncate_table(table)
        print("done")


def insert_rows(table: str, rows: list):
    """Insert rows in batches via POST (upsert — ignore conflicts on PK).

    Generated columns (e.g. point_diff in session_wrapped_stats) are stripped
    from each row before sending — the database computes them automatically.
    """
    skip_cols = GENERATED_COLUMNS.get(table, set())
    if skip_cols:
        rows = [{k: v for k, v in row.items() if k not in skip_cols} for row in rows]

    total   = len(rows)
    headers = dict(HEADERS)
    headers["Prefer"] = "resolution=ignore-duplicates,return=minimal"

    for start in range(0, total, BATCH_SIZE):
        batch = rows[start : start + BATCH_SIZE]
        url   = f"{SUPABASE_URL}/rest/v1/{table}"
        data  = json.dumps(batch).encode("utf-8")
        req   = urllib.request.Request(url, data=data, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                resp.read()
        except urllib.error.HTTPError as e:
            body_text = e.read().decode("utf-8", errors="replace")
            raise RuntimeError(
                f"Insert failed on {table} (rows {start}–{start+len(batch)-1}): "
                f"HTTP {e.code}: {body_text}"
            )
        print(f"  {table}: inserted rows {start+1}–{min(start+BATCH_SIZE, total)} / {total}")


# ── SQL parser ────────────────────────────────────────────────────────────────
# Parses the JSON data files alongside the SQL backup if they exist,
# otherwise falls back to parsing INSERT statements from the .sql file.

def parse_backup_sql(sql_path: Path) -> dict[str, list[dict]]:
    """
    Reads the .sql backup and extracts rows per table as list-of-dicts.
    Looks for INSERT INTO public.<table> (<cols>) VALUES (<vals>); lines.
    This is a best-effort parser that handles the output of run_backup.py.
    """
    text   = sql_path.read_text(encoding="utf-8")
    result: dict[str, list] = {t: [] for t in INSERT_ORDER}

    # Match INSERT lines: INSERT INTO public.TABLE (col1, col2) VALUES (v1, v2);
    insert_re = re.compile(
        r"INSERT INTO public\.(\w+)\s*\(([^)]+)\)\s*VALUES\s*\((.+)\);",
        re.IGNORECASE,
    )

    for line in text.splitlines():
        line = line.strip()
        if not line.upper().startswith("INSERT"):
            continue
        m = insert_re.match(line)
        if not m:
            continue
        table  = m.group(1)
        cols   = [c.strip() for c in m.group(2).split(",")]
        vals_s = m.group(3)

        # Parse value list — respects single-quoted strings, ::casts, NULL, TRUE/FALSE
        vals = _parse_values(vals_s)
        if len(vals) != len(cols):
            print(f"  WARNING: col/val mismatch on {table}, skipping row")
            continue

        row = {}
        for col, val in zip(cols, vals):
            row[col] = val

        if table in result:
            result[table].append(row)

    return result


def _parse_values(vals_s: str) -> list:
    """
    Split a SQL VALUES clause into a Python list, handling:
      - NULL → None
      - TRUE/FALSE → bool
      - integers/floats → numbers
      - 'single-quoted strings' with '' escaping → str
      - 'json'::jsonb → dict/list (parsed as JSON)
    """
    tokens = []
    i = 0
    s = vals_s.strip()

    while i < len(s):
        ch = s[i]

        if ch in (" ", "\t"):
            i += 1
            continue

        if ch == ",":
            i += 1
            continue

        # Quoted string
        if ch == "'":
            j = i + 1
            buf = []
            while j < len(s):
                if s[j] == "'" and j + 1 < len(s) and s[j + 1] == "'":
                    buf.append("'")
                    j += 2
                elif s[j] == "'":
                    j += 1
                    break
                else:
                    buf.append(s[j])
                    j += 1
            raw = "".join(buf)
            # Skip ::cast suffix (e.g. ::jsonb, ::text)
            rest = s[j:]
            cast_m = re.match(r"^::[a-zA-Z_]+", rest)
            if cast_m:
                j += len(cast_m.group(0))
                # If it's a jsonb cast, parse as JSON
                try:
                    tokens.append(json.loads(raw))
                except (json.JSONDecodeError, ValueError):
                    tokens.append(raw)
            else:
                tokens.append(raw)
            i = j
            continue

        # Unquoted token (NULL, TRUE, FALSE, number)
        j = i
        while j < len(s) and s[j] not in (",", "'"):
            j += 1
        token = s[i:j].strip()
        i = j

        # Strip trailing ::cast from unquoted tokens
        token = re.sub(r"::[a-zA-Z_]+$", "", token).strip()

        upper = token.upper()
        if upper == "NULL":
            tokens.append(None)
        elif upper == "TRUE":
            tokens.append(True)
        elif upper == "FALSE":
            tokens.append(False)
        else:
            try:
                tokens.append(int(token))
            except ValueError:
                try:
                    tokens.append(float(token))
                except ValueError:
                    tokens.append(token)

    return tokens


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 backups/run_restore.py <backup.sql>")
        sys.exit(1)

    sql_path = Path(sys.argv[1])
    if not sql_path.exists():
        print(f"Error: file not found: {sql_path}")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"  Badminton App — Supabase restore")
    print(f"  Source : {sql_path.name}")
    print(f"{'='*60}\n")

    # ── Parse backup ──────────────────────────────────────────────
    print("Parsing backup file…")
    data = parse_backup_sql(sql_path)

    # Summary
    print("\nBackup contents:")
    total = 0
    for table in INSERT_ORDER:
        count = len(data.get(table, []))
        total += count
        print(f"  {table:<30} {count:>5} rows")
    print(f"  {'TOTAL':<30} {total:>5} rows")

    # ── Confirmation ──────────────────────────────────────────────
    print(f"\n⚠️  This will DELETE ALL current data in these tables and")
    print(f"   replace it with the backup. This cannot be undone.")
    print(f"\n   Tables affected: {', '.join(TRUNCATE_ORDER)}")
    confirm = input("\nType YES to proceed: ").strip()
    if confirm != "YES":
        print("Aborted.")
        sys.exit(0)

    # ── Truncate ──────────────────────────────────────────────────
    truncate_all(TRUNCATE_ORDER)

    # ── Insert ────────────────────────────────────────────────────
    # We re-truncate each table right before inserting its rows.
    # This handles trigger-created rows: e.g. inserting `sessions` may fire
    # a trigger that auto-populates `session_organizers`, so by the time we
    # reach that table in INSERT_ORDER it already has rows we need to clear.
    print("\nInserting rows…")
    for table in INSERT_ORDER:
        rows = data.get(table, [])
        if not rows:
            print(f"  {table}: 0 rows — skipping")
            continue
        # Clear any rows that may have appeared since initial truncation
        # (due to triggers fired by parent-table inserts above).
        truncate_table(table)
        try:
            insert_rows(table, rows)
        except RuntimeError as e:
            print(f"\n❌ ERROR: {e}")
            print("Restore aborted mid-way. DB may be in a partial state.")
            print("Re-run the script or restore via the Supabase SQL Editor.")
            sys.exit(1)

    print(f"\n{'='*60}")
    print(f"  Restore complete — {total} rows written")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
