// ============================================================
// Playwright Configuration — Zero-Local E2E Suite
// ============================================================
// Tests run against the live Vercel deployment (TEST_BASE_URL).
// No webServer block — we never spin up a local dev server.
//
// All specs share one TEST_SESSION_ID (sandbox session in the
// production Supabase project), so they run serially (workers: 1).
//
// Usage:
//   cp .env.test.example .env.test   # fill in your secrets
//   npx playwright test              # run all specs
//   npx playwright test --ui         # interactive UI mode
// ============================================================

import { defineConfig, devices } from "@playwright/test";
import dotenv from "dotenv";
import path from "path";

// Load .env.test (gitignored) — contains TEST_SESSION_ID, keys, BASE_URL.
// Falls back to .env.local so dev machines don't need a separate file.
dotenv.config({ path: path.resolve(__dirname, ".env.test") });
dotenv.config({ path: path.resolve(__dirname, ".env.local"), override: false });

// ── Vercel Deployment Protection bypass ───────────────────────
// When Vercel Authentication is enabled (team plan), all deployments
// require a Vercel login. There are two ways to bypass this for E2E:
//
// 1. VERCEL_BYPASS_SECRET (recommended for CI):
//    Vercel Dashboard → Project Settings → General →
//    "Deployment Protection" → "Protection Bypass for Automation"
//    Copy the generated secret here.
//    Playwright sends it as the x-vercel-protection-bypass header
//    on every request, which Vercel accepts without a login.
//
// 2. VERCEL_SHARE_URL (temporary, 23-hour window):
//    A _vercel_share=<token> URL generated by the Vercel MCP tool.
//    The auth fixture navigates to it once to get the bypass cookie,
//    then proceeds. Regenerate when expired: npm run test:vercel-auth
//
// If neither is set, tests will hit the Vercel login wall.
const vercelBypassSecret = process.env.VERCEL_BYPASS_SECRET;

// ── Fatal boot guard ──────────────────────────────────────────
// Fail loudly at config load time rather than mid-run if the
// critical environment variables are missing.
const requiredEnv = [
  "TEST_BASE_URL",
  "TEST_SESSION_ID",
  "NEXT_PUBLIC_SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
];

for (const key of requiredEnv) {
  if (!process.env[key]) {
    throw new Error(
      `[playwright.config] Missing required env var: ${key}\n` +
        `Copy .env.test.example → .env.test and fill in all values.`
    );
  }
}

export default defineConfig({
  testDir: "./tests/e2e",

  // Last-resort sandbox sweep. Per-spec afterAll hooks are skipped on Ctrl-C,
  // a hard test timeout, or a crash — which would strand scenario I's 50 bot
  // accounts in the production profiles table. See tests/helpers/global-teardown.ts.
  globalTeardown: "./tests/helpers/global-teardown.ts",

  // ── Execution ─────────────────────────────────────────────
  // Serial: all specs share one sandbox session — parallel runs
  // would corrupt each other's state.
  fullyParallel: false,
  workers: 1,

  // Retry flaky tests twice in CI; fail fast locally.
  retries: process.env.CI ? 2 : 0,

  // ── Reporters ─────────────────────────────────────────────
  reporter: [["list"], ["html", { outputFolder: "playwright-report", open: "never" }]],

  // ── Global settings ────────────────────────────────────────
  use: {
    baseURL: process.env.TEST_BASE_URL,

    // Keep a full trace on failure for debugging.
    trace: "retain-on-failure",

    // Screenshot on failure.
    screenshot: "only-on-failure",

    // 10s action timeout — generous for realtime propagation.
    actionTimeout: 10_000,

    // 30s navigation timeout (cold Vercel edge can be slow).
    navigationTimeout: 30_000,

    // Bypass Vercel Deployment Protection on every request.
    // Only active when VERCEL_BYPASS_SECRET is configured.
    ...(vercelBypassSecret
      ? { extraHTTPHeaders: { "x-vercel-protection-bypass": vercelBypassSecret } }
      : {}),
  },

  // ── Timeout ───────────────────────────────────────────────
  // 60s per test — includes DB setup + UI interactions + assertions.
  timeout: 60_000,

  // ── Projects ──────────────────────────────────────────────
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
