"""Shared emitter for the compute_session_wrapped server-side reconstruction.

WHY THIS EXISTS AT ALL

  The only channel to production here is the Supabase MCP, and `apply_migration`
  STRIPS NON-ASCII from stored function bodies. This body holds 35 of them: 32
  box-drawing rules and 2 bullets inside comments, and one em-dash inside a
  string a player actually reads --

      'Come back next session - your story is just beginning.'

  -- the just_getting_started award copy. Shipping the body through
  apply_migration would silently mangle that line and put production's prosrc
  permanently out of md5-agreement with the repo file.

  So nothing ships the body. These scripts read production's OWN prosrc, replay
  the same anchored substitutions ON THE SERVER, and gate the DDL on md5. The
  non-ASCII is never retransmitted, so it cannot be stripped. This is the same
  method 20260811000000 was applied by; see MEMORY.md "How the two 20260811*
  were actually applied".

  Run the emitted SQL through execute_sql, not apply_migration -- the point is
  to avoid that path, and the emitted text is pure ASCII by construction.
"""

import hashlib


def _sql_literal(preamble: str) -> str:
    """The CREATE clause as it must appear inside a single-quoted EXECUTE string.

    The baseline's clause ends 'AS $function$'; the emitted EXECUTE supplies its
    own $body$ tag, so the dollar-quote tag is dropped here and the clause is
    handed back ending in 'AS '. Single quotes are doubled for the enclosing
    literal, which is what turns SET search_path TO 'public', 'pg_temp' into the
    ''public'', ''pg_temp'' the EXECUTE needs.
    """
    tail = "AS $function$"
    flat = " ".join(preamble.split())
    if not flat.endswith(tail):
        raise SystemExit(f"ABORT: preamble does not end in {tail!r}: {flat[-60:]!r}")
    return flat[: -len(tail)].replace("'", "''") + "AS "


def emit(*, generator: str, migration: str, preamble: str, body: str, subs, baseline_md5: str):
    """Return (verify_sql, apply_sql, target_md5).

    `subs` is the same [(old, new, label)] list the generator applies locally, so
    the check can never drift from the migration it is checking.
    """
    target = hashlib.md5(("\n" + body).encode("utf-8")).hexdigest()

    for old, new, label in subs:
        for tag in ("$s$", "$r$", "$body$", "$verify$", "$apply$", "$acl$"):
            if tag in old or tag in new:
                raise SystemExit(f"ABORT: substitution {label!r} contains dollar-quote tag {tag}")
    for old, new, label in subs:
        if not old.isascii() or not new.isascii():
            raise SystemExit(f"ABORT: substitution {label!r} is not ASCII; it would be stripped")

    steps = []
    for i, (old, new, label) in enumerate(subs, 1):
        steps.append(
            f"  -- {i}. {label}\n"
            f"  v_needle := $s${old}$s$;\n"
            f"  v_n := (length(v_src) - length(replace(v_src, v_needle, ''))) / length(v_needle);\n"
            f"  IF v_n <> 1 THEN RAISE EXCEPTION 'ANCHOR {i} ({label}) matched % times in production, expected 1', v_n; END IF;\n"
            f"  v_src := replace(v_src, v_needle, $r${new}$r$);\n"
        )
    steps_sql = "\n".join(steps)
    n = len(subs)
    sig = _sql_literal(preamble)

    read = (
        "  SELECT p.prosrc INTO v_src FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace\n"
        "   WHERE n.nspname = 'public' AND p.proname = 'compute_session_wrapped';\n"
        "  IF v_src IS NULL THEN RAISE EXCEPTION 'compute_session_wrapped not found'; END IF;\n"
    )

    verify = (
        f"-- GENERATED by {generator} --verify-sql\n"
        f"-- Read-only rehearsal of {migration}. Always ends in RAISE EXCEPTION, so it\n"
        "-- rolls back and mutates nothing. Run through execute_sql.\n"
        "DO $verify$\n"
        "DECLARE\n"
        "  v_src text; v_needle text; v_n int;\n"
        f"  v_base text := '{baseline_md5}';\n"
        f"  v_want text := '{target}';\n"
        "BEGIN\n"
        + read
        + "  RAISE NOTICE 'production prosrc: % bytes, md5 %', length(v_src), md5(v_src);\n"
        "  IF md5(v_src) = v_want THEN RAISE EXCEPTION 'ALREADY APPLIED: body is already md5 %', v_want; END IF;\n"
        "  IF md5(v_src) <> v_base THEN\n"
        "    RAISE EXCEPTION 'DRIFT: production is md5 % (% bytes), this script chains off % -- regenerate', md5(v_src), length(v_src), v_base;\n"
        "  END IF;\n\n"
        + steps_sql
        + "\n  IF md5(v_src) <> v_want THEN\n"
        "    RAISE EXCEPTION 'RECONSTRUCTION MISMATCH: rebuilt md5 % (% bytes), repo file is %', md5(v_src), length(v_src), v_want;\n"
        "  END IF;\n\n"
        "  -- Prove it compiles without touching the real function.\n"
        f"  EXECUTE 'CREATE FUNCTION pg_temp.compute_session_wrapped_verify(p_session_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''public'', ''pg_temp'' AS $body$' || v_src || '$body$';\n\n"
        f"  RAISE EXCEPTION 'VERIFY OK -- {n}/{n} anchors matched once, md5 = %, body compiles. Rolling back.', v_want;\n"
        "END\n"
        "$verify$;\n"
    )

    apply = (
        f"-- GENERATED by {generator} --apply-sql\n"
        f"-- Applies {migration} by reconstructing its body server-side from\n"
        f"-- production's own prosrc and gating the DDL on md5 = {target}.\n"
        "-- The readable equivalent is the repo migration; this is byte-equivalent to it\n"
        "-- by construction and proves so BEFORE it writes. Any failed check raises\n"
        "-- before the DDL, so a bad run applies nothing. Idempotent.\n"
        "--\n"
        "-- Run through execute_sql. NOT apply_migration: that strips non-ASCII from\n"
        "-- stored function bodies and this body has 35, one of them in player-facing\n"
        "-- award copy.\n"
        "DO $apply$\n"
        "DECLARE\n"
        "  v_src text; v_needle text; v_after text; v_n int;\n"
        f"  v_base text := '{baseline_md5}';\n"
        f"  v_want text := '{target}';\n"
        "BEGIN\n"
        + read
        + "\n  IF md5(v_src) = v_want THEN\n"
        "    RAISE NOTICE 'ALREADY APPLIED: body is already md5 %. Nothing to do.', v_want;\n"
        "    RETURN;\n"
        "  END IF;\n\n"
        "  IF md5(v_src) <> v_base THEN\n"
        "    RAISE EXCEPTION 'DRIFT: production is md5 % (% bytes), this script chains off % -- NOTHING APPLIED', md5(v_src), length(v_src), v_base;\n"
        "  END IF;\n\n"
        "  -- The reconstruction wraps the body in $body$; if production's own text ever\n"
        "  -- contained that tag the generated DDL would terminate early and mangle it.\n"
        "  IF position('$body$' in v_src) > 0 THEN\n"
        "    RAISE EXCEPTION 'production body contains the dollar-quote tag this script uses';\n"
        "  END IF;\n\n"
        "  RAISE NOTICE 'pre-apply prosrc: % bytes, md5 %', length(v_src), md5(v_src);\n\n"
        + steps_sql
        + "\n  IF md5(v_src) <> v_want THEN\n"
        "    RAISE EXCEPTION 'RECONSTRUCTION MISMATCH: rebuilt md5 % (% bytes), expected % -- NOTHING APPLIED', md5(v_src), length(v_src), v_want;\n"
        "  END IF;\n\n"
        f"  EXECUTE '{sig}$body$' || v_src || '$body$';\n\n"
        + "  SELECT p.prosrc INTO v_after FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace\n"
        "   WHERE n.nspname = 'public' AND p.proname = 'compute_session_wrapped';\n"
        "  IF md5(v_after) <> v_want THEN\n"
        "    RAISE EXCEPTION 'POST-APPLY MISMATCH: stored body is md5 %, expected %', md5(v_after), v_want;\n"
        "  END IF;\n\n"
        f"  RAISE NOTICE 'APPLIED: {n}/{n} anchors matched once, body now % bytes, md5 %', length(v_after), v_want;\n"
        "END\n"
        "$apply$;\n\n"
        "-- CREATE OR REPLACE already preserves owner and ACL; restated as an assertion\n"
        "-- of intent, not a widening.\n"
        "grant execute on function public.compute_session_wrapped(uuid) to postgres with grant option;\n"
        "grant execute on function public.compute_session_wrapped(uuid) to service_role;\n\n"
        "-- Fail loudly if anon/authenticated ever appear on this function.\n"
        "DO $acl$\n"
        "DECLARE v_acl text;\n"
        "BEGIN\n"
        "  SELECT p.proacl::text INTO v_acl FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace\n"
        "   WHERE n.nspname = 'public' AND p.proname = 'compute_session_wrapped';\n"
        "  IF v_acl LIKE '%anon=%' OR v_acl LIKE '%authenticated=%' THEN\n"
        "    RAISE EXCEPTION 'ACL WIDENED: %', v_acl;\n"
        "  END IF;\n"
        "  RAISE NOTICE 'acl ok: %', v_acl;\n"
        "END\n"
        "$acl$;\n"
    )
    return verify, apply, target
