#!/usr/bin/env python3
"""Generate 20260821000000 -- exclude hidden sessions from the "prior session" set.

Chained off 20260820000000, NOT off the 20260811000000 baseline: that migration
already rewrote both CTEs this one touches, so generating from the older body
would silently revert the as-of bound. The baseline pinned below is therefore
the body 20260820000000 declares, which must equal production's pg_proc.prosrc
AFTER 20260820000000 is applied:

    select md5(p.prosrc), length(p.prosrc) from pg_proc p
      join pg_namespace n on n.oid=p.pronamespace
     where p.proname='compute_session_wrapped' and n.nspname='public';

WHAT THIS CHANGES

  prior_sessions_ranked and prior_carry select the sessions that count as "the
  night before" for bounced_back, consistent_dominator and momentum. Both join
  `sessions` already (20260820000000 added the join to order by the session
  clock) but neither filters `is_hidden`, so a hidden session's wrap can serve
  as somebody's previous night.

  _prior_awards -- the one-time-award ledger added by 20260811000000 -- has
  filtered `is_hidden=false` since the day it was written. These two CTEs are
  the only readers of session_wrapped_stats that do not, which is what makes
  this an inconsistency rather than a design choice.

WHY IT IS SAFE TO DO NOW, AND WOULD NOT BE LATER

  Measured on production 2026-08-20: 30 sessions, 28 hold wraps, 2 are hidden,
  and 0 hidden sessions hold a wrap. So on today's data this migration cannot
  change a single stored award -- it is provably inert. Once a hidden session
  does accumulate a wrap the same change silently revokes badges from players
  who can see them, which is a materially different migration to ship.

NOT IN SCOPE

  Which sessions get hidden, and whether hiding one should retroactively drop
  its wraps. This bounds the READ only.
"""

import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _wrapped_apply_sql import emit  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "supabase/migrations/20260820000000_wrapped_reads_the_ledger_as_of_this_session.sql"
OUT = ROOT / "supabase/migrations/20260821000000_prior_sessions_exclude_hidden.sql"

# md5 of ('\n' + body), i.e. exactly what pg_proc.prosrc holds once 20260820000000 lands.
BASELINE_MD5 = "d459753ba1501da34691de5c00979a3d"


def extract_body(sql: str) -> str:
    i = sql.index("AS $function$\n") + len("AS $function$\n")
    j = sql.index("\n$function$", i)
    return sql[i : j + 1]


def extract_preamble(sql: str) -> str:
    """The CREATE clause verbatim from BASE, never retyped.

    Retyping it is not hypothetical: the first draft of this generator hand-wrote
    the clause and dropped 'pg_temp' from search_path. The body CREATEs four TEMP
    tables, and CREATE OR REPLACE rewrites proconfig wholesale, so that silently
    changed a function attribute production has held since 20260811000000 --
    while every test still passed, because Postgres searches the temp schema for
    TABLES regardless of search_path. Deriving it makes the class impossible.
    """
    i = sql.index("CREATE OR REPLACE FUNCTION public.compute_session_wrapped")
    j = sql.index("AS $function$\n", i) + len("AS $function$\n")
    return sql[i:j]


def sub_once(body: str, old: str, new: str, label: str) -> str:
    n = body.count(old)
    if n != 1:
        sys.exit(f"ABORT: anchor '{label}' matched {n} times, expected exactly 1")
    return body.replace(old, new)


# The two aliases are distinct (ps = prior_sessions_ranked, cs = prior_carry),
# so each anchor is unique on its own without carrying the whole CTE text.
SUBS = [
    (
        "AND ps.created_at<v_session_start ",
        "AND ps.created_at<v_session_start AND ps.is_hidden=false ",
        "prior_sessions_ranked is_hidden",
    ),
    (
        "AND cs.created_at<v_session_start ",
        "AND cs.created_at<v_session_start AND cs.is_hidden=false ",
        "prior_carry is_hidden",
    ),
]

HEADER = """-- 20260821000000_prior_sessions_exclude_hidden.sql
--
-- A hidden session's wrap could serve as another session's "previous night".
--
-- prior_sessions_ranked (bounced_back, consistent_dominator) and prior_carry
-- (momentum) are the only readers of session_wrapped_stats that did not filter
-- sessions.is_hidden. _prior_awards has filtered it since 20260811000000, so
-- this closes an inconsistency between three CTEs over one table, not a new
-- product rule.
--
-- Generated by scripts/gen-prior-sessions-hidden-migration.py from the body
-- 20260820000000 declares (md5 d459753ba1501da34691de5c00979a3d over
-- '\\n'||prosrc, 52094 chars). Regenerate rather than hand-edit; the generator
-- refuses to run if that baseline moved.
--
-- APPLY ORDER: strictly after 20260820000000. Applied on its own to an
-- unmigrated production this would revert the as-of bound.
--
-- Inert on the data it shipped against: 0 of production's 28 wrapped sessions
-- were hidden on 2026-08-20. Pinned by Suite XS-7, which fails against the
-- pre-20260821000000 function.

"""

FOOTER = """$function$;

-- Privileges are preserved across CREATE OR REPLACE; restated so a from-scratch
-- replay lands on the same grants production has. Restate the GRANTs BEFORE the
-- REVOKE: `revoke ... from public` also strips EXECUTE from service_role on a
-- database built from scratch (see docs -- revoke-strips-service-role).
grant execute on function public.compute_session_wrapped(uuid) to postgres with grant option;
grant execute on function public.compute_session_wrapped(uuid) to service_role;
revoke execute on function public.compute_session_wrapped(uuid) from public, anon, authenticated;

comment on function public.compute_session_wrapped(uuid) is
  'Computes and stores Session Wrapped stats + awards for one session. Every cross-session figure is as of the END of that session: the running ledgers are read, then everything from this session onward is subtracted back out, so a recompute of an old session (fixPlayerRecord) cannot count the player''s later matches as history. Bounded by 20260820000000; hidden sessions excluded from the prior-session set by 20260821000000.';
"""



def _flag_dest(flag: str) -> Path:
    """Resolve <path> for a flag. <path> is an OUTPUT destination, not an input.

    `--apply-sql <the migration>` reads naturally as "apply this file" and would
    instead overwrite the 54 KB migration with a ~12 KB DO block. That was done
    for real on 2026-08-11 against the sibling generator; refuse it here.
    """
    try:
        raw = sys.argv[sys.argv.index(flag) + 1]
    except IndexError:
        sys.exit(f"ABORT: {flag} needs an output path, e.g. {flag} /tmp/out.sql")
    if raw.startswith("--"):
        sys.exit(f"ABORT: {flag} needs an output path but got the flag {raw!r}")
    p = Path(raw)

    def _same(a: Path, b: Path) -> bool:
        if a.resolve() == b.resolve():
            return True
        if a.exists() and b.exists():
            sa, sb = a.stat(), b.stat()
            return (sa.st_dev, sa.st_ino) == (sb.st_dev, sb.st_ino)  # hardlink
        return False

    for guard, what in ((OUT, "the migration"), (BASE, "the baseline")):
        if _same(p, guard):
            sys.exit(
                f"ABORT: {flag} <path> is an OUTPUT destination, and you pointed it at "
                f"{what} ({guard.name}). Use a scratch path."
            )
    if not p.parent.exists():
        sys.exit(f"ABORT: {flag} <path> directory does not exist: {p.parent}")
    return p

def main() -> None:
    base_sql = BASE.read_text(encoding="utf-8")
    body = extract_body(base_sql)
    preamble = extract_preamble(base_sql)

    # Cheap assertion of the one attribute the hand-written draft got wrong, so a
    # future edit to BASE that drops it cannot ride through silently.
    if "'public', 'pg_temp'" not in preamble:
        sys.exit(f"ABORT: BASE's search_path is not 'public', 'pg_temp':\n{preamble}")

    got = hashlib.md5(("\n" + body).encode("utf-8")).hexdigest()
    if got != BASELINE_MD5:
        sys.exit(
            f"ABORT: baseline body md5 is {got}, expected {BASELINE_MD5}.\n"
            f"  {BASE.name} no longer declares the body this generator chains "
            f"off. Re-verify against pg_proc before regenerating."
        )

    for old, new, label in SUBS:
        body = sub_once(body, old, new, label)

    # Every reader of session_wrapped_stats now filters hidden sessions:
    # _prior_awards (pre-existing) plus the two this migration bounds.
    hidden = body.count("is_hidden=false")
    if hidden != 4:
        sys.exit(f"ABORT: {hidden} is_hidden filters, expected 4")

    # The as-of bound from 20260820000000 must survive intact.
    for anchor in ("ps.created_at<v_session_start", "cs.created_at<v_session_start"):
        if body.count(anchor) != 1:
            sys.exit(f"ABORT: as-of bound '{anchor}' did not survive the rewrite")

    reads = body.count("player_rivalries") + body.count("player_partnerships")
    if reads != 2:
        sys.exit(f"ABORT: {reads} ledger reads remain, expected 2")

    added = [ch for ch in body if ord(ch) > 127]
    if len(added) != 35:
        sys.exit(
            f"ABORT: body holds {len(added)} non-ASCII characters, expected the "
            f"baseline's 35 -- apply_migration strips non-ASCII from stored "
            f"function bodies, so added text must be ASCII-only"
        )

    flag_mode = "--verify-sql" in sys.argv or "--apply-sql" in sys.argv
    if flag_mode:
        # Read-only by contract: the body stays in memory and OUT is untouched.
        verify_sql, apply_sql, target = emit(
            generator=Path(__file__).name,
            migration="20260821000000_prior_sessions_exclude_hidden.sql",
            preamble=preamble,
            body=body,
            subs=SUBS,
            baseline_md5=BASELINE_MD5,
        )
        if "--verify-sql" in sys.argv:
            d = _flag_dest("--verify-sql"); d.write_text(verify_sql, encoding="utf-8")
            print(f"wrote {d}")
        if "--apply-sql" in sys.argv:
            d = _flag_dest("--apply-sql"); d.write_text(apply_sql, encoding="utf-8")
            print(f"wrote {d}")
        print(f"target md5 = {target}  ({len(SUBS)} substitutions)")
        return

    OUT.write_text(HEADER + preamble + body + FOOTER, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
